name: Lint & Format
permissions:
  contents: read

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build 
        pip install -e .[dev]
    - name: Run black
      run: black --check .
    - name: Run isort
      run: isort --check-only .
    - name: Run flake8
      run: flake8 .